import React from "react";
import CodeHighlighter from "../../components/CodeHighlighter";

const IoTDevicesAndPlatforms = () => {
  const codeString = `
  import boto3
  # Create an AWS IoT client
  iot_client = boto3.client('iot-data', region_name='us-east-1')
  # Publish a message to a topic
  response = iot_client.publish(
      topic='mytopic',
      qos=1,
      payload='Hello, IoT!'
  )
  # Print the response
  print(response)
  
  `;
  const codeString1 = `
  from google.cloud import iot_v1
  # Create a client
  client = iot_v1.DeviceManagerClient()
  # Define the device path
  device_path = client.device_path('my-project', 'my-region', 'my-registry', 'my-device')
  # Create the telemetry event
  event_data = 'Temperature: 25°C'
  # Publish the event
  client.send_command_to_device(
      request={
          'name': device_path,
          'binary_data': event_data.encode('utf-8')
      }
  )
  
  `;
  const codeString2 = `
  from azure.iot.device import IoTHubDeviceClient
  # Create an IoT Hub device client
  device_client = IoTHubDeviceClient.create_from_connection_string('<your_connection_string>')
  # Connect to IoT Hub
  device_client.connect()
  # Send a message
  message = 'Hello, IoT!'
  device_client.send_message(message)
  # Disconnect from IoT Hub
  device_client.disconnect()
  
  `;
  return (
    <div>
      {" "}
      <section className="p-4 md:text-base text-justify text-sm">
        <article className="mt-6">
          <h4 className="p-2 text-lg font-bold rounded-md card-bg w-full">
            IoT platforms for device management and data processing (e.g., AWS
            IoT, Google Cloud IoT, Microsoft Azure IoT)
          </h4>
          <p className="text-justify p-2 pt-4">
            <span className="font-semibold">
              1. AWS IoT (Amazon Web Services IoT):
            </span>{" "}
            AWS IoT is a platform provided by Amazon Web Services that helps you
            connect, manage, and analyze IoT devices and their data. Here's a
            simplified explanation of AWS IoT:
          </p>

          <ul className="list-disc px-10">
            <li className="pt-4">
              AWS IoT provides a secure and scalable infrastructure for
              connecting and managing IoT devices.
            </li>
            <li className="pt-4">
              It offers device management features, allowing you to securely
              register and organize your IoT devices in the cloud.
            </li>
            <li className="pt-4">
              AWS IoT provides software development kits (SDKs) that help
              developers write code to connect and interact with IoT devices.
            </li>
            <li className="pt-4">
              It supports various communication protocols like MQTT, which
              allows devices to publish and subscribe to messages.
            </li>
            <li className="pt-4">
              AWS IoT also provides services for data processing, storage, and
              analytics, allowing you to analyze and gain insights from the data
              generated by your IoT devices.
            </li>
          </ul>
          <p className="text-justify p-2 pt-4">
            For example, you can use AWS IoT to connect and control a smart
            thermostat from a mobile app, store temperature data in the cloud,
            and analyze the data to identify patterns.
          </p>
          <h4 className="p-2 text-lg font-bold">
            Here's a simple Python code example that demonstrates how to publish
            a message to AWS IoT using the AWS SDK:
          </h4>
          <CodeHighlighter>{codeString}</CodeHighlighter>
          <p className="text-justify p-2 pt-4">
            <span className="font-semibold">2. Google Cloud IoT:</span> Google
            Cloud IoT is a platform provided by Google Cloud that enables you to
            connect, manage, and process data from IoT devices. Here's a
            simplified explanation of Google Cloud IoT:
          </p>

          <ul className="list-disc px-10">
            <li className="pt-4">
              Google Cloud IoT offers device registry and management features,
              allowing you to register and manage your IoT devices in the cloud.
            </li>
            <li className="pt-4">
              It supports multiple communication protocols like MQTT and HTTP,
              making it easy for devices to send and receive data.
            </li>
            <li className="pt-4">
              Google Cloud IoT Core is a service that provides a scalable
              infrastructure for securely connecting and managing devices at
              scale.
            </li>
            <li className="pt-4">
              It integrates with other Google Cloud services, such as Pub/Sub
              for messaging, Cloud Functions for serverless processing, and
              BigQuery for data analytics.
            </li>
          </ul>
          <p className="text-justify p-2 pt-4">
            For example, you can use Google Cloud IoT to collect data from a
            fleet of smart vehicles, process the data in real-time, and
            visualize it on a dashboard.
          </p>
          <h4 className="p-2 text-lg font-bold">
            Here's a simple Python code example that demonstrates how to send a
            telemetry event to Google Cloud IoT using the Google Cloud IoT
            Python library:
          </h4>
          <CodeHighlighter>{codeString1}</CodeHighlighter>
          <p className="text-justify p-2 pt-4">
            <span className="font-semibold">3. Microsoft Azure IoT: </span>
            Microsoft Azure IoT is a platform provided by Microsoft Azure that
            helps you build, deploy, and manage IoT solutions. Here's a
            simplified explanation of Microsoft Azure IoT:
          </p>

          <ul className="list-disc px-10">
            <li className="pt-4">
              Azure IoT Hub is a central component of Azure IoT that enables
              secure communication and management of IoT devices.
            </li>
            <li className="pt-4">
              It provides device management features, allowing you to provision,
              configure, and monitor your IoT devices.
            </li>
            <li className="pt-4">
              Azure IoT Hub supports various communication protocols like MQTT
              and HTTP, making it easy for devices to connect and send data.
            </li>
            <li className="pt-4">
              It integrates with other Azure services like Azure Functions,
              Azure Stream Analytics, and Azure Machine Learning, enabling you
              to process and analyze data from IoT devices.
            </li>
          </ul>
          <p className="text-justify p-2 pt-4">
            For example, you can use Azure IoT Hub to collect sensor data from a
            network of weather stations, store the data in Azure Storage, and
            visualize it on a web-based dashboard.
          </p>
          <h4 className="p-2 text-lg font-bold">
            Here's a simple code example using Azure IoT SDK for Python that
            demonstrates how to send a message to Azure IoT Hub:
          </h4>
          <CodeHighlighter>{codeString2}</CodeHighlighter>

          <p className="text-justify p-2 pt-4">
            Please note that the code examples provided are simplified and may
            require additional setup and configuration. Additionally, it's
            important to review the official documentation and resources
            provided by each platform for a more comprehensive understanding of
            their features and capabilities.
          </p>
          <p className="text-justify p-2 pt-4">
            In summary, AWS IoT, Google Cloud IoT, and Microsoft Azure IoT are
            platforms that provide infrastructure, tools, and services for
            managing IoT devices and processing data generated by those devices.
            They offer features like device management, communication protocols,
            and integration with other cloud services to build scalable and
            secure IoT solutions.
          </p>
        </article>
      </section>
    </div>
  );
};

export default IoTDevicesAndPlatforms;
