import React from "react";
import CodeHighlighter from "../../components/CodeHighlighter";

const IoTIntroHistorical = () => {
  const codeString = `// Include the necessary libraries
  #include <WiFi.h>
  #include <Adafruit_NeoPixel.h>
  // Define Wi-Fi credentials
  const char* ssid = "YourNetworkSSID";
  const char* password = "YourNetworkPassword";
  // Define the number of LEDs in the NeoPixel strip
  const int numPixels = 1;
  // Create an instance of the NeoPixel library
  Adafruit_NeoPixel strip(numPixels, 4, NEO_GRB + NEO_KHZ800);
  void setup() {
    // Connect to Wi-Fi
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) {
      delay(1000);
    }
  // Initialize the NeoPixel strip
    strip.begin();
    strip.show();
  }
  void loop() {
  // Code for controlling the light bulb goes here
  }
  
  `;
  return (
    <div>
      <section className="p-4 md:text-base text-justify text-sm">
        <article className="mt-6">
          <h4 className="p-2 text-lg font-bold rounded-md card-bg w-full">
            {" "}
            Historical background and evolution of IoT
          </h4>
          <p className="text-justify p-2 pt-4">
            Historical Background: The concept of IoT has its roots in the early
            development of the internet and the increasing connectivity of
            devices. In the 1980s and 1990s, computers started becoming more
            common, and the internet began to grow. During this time, people
            started to connect computers together to share information and
            communicate.
          </p>
          <h4 className="p-2 text-lg font-bold">
            {" "}
            Evolution of IoT:
          </h4>

          <ul className="list-disc px-10">
            <li className="pt-4">
              <span class="font-semibold"> Internet and Connectivity:</span>The
              internet played a crucial role in the evolution of IoT. As more
              devices became capable of connecting to the internet, the idea of
              connecting physical objects to enhance their functionality
              emerged.
            </li>
            <li className="pt-4">
              <span class="font-semibold"> RFID Technology:</span>One of the
              early technologies that contributed to the development of IoT was
              Radio Frequency Identification (RFID). RFID tags are small chips
              that can be attached to objects to identify and track them using
              radio waves. They are commonly used in inventory management
              systems and access control. For example, some libraries use RFID
              tags to track books.
            </li>
            <li className="pt-4">
              <span class="font-semibold">Sensor Technology:</span>Advancements
              in sensor technology played a significant role in the evolution of
              IoT. Sensors are devices that can detect and measure physical
              properties like temperature, humidity, light, motion, and more. As
              sensors became smaller, cheaper, and more energy-efficient, they
              started being incorporated into various objects.
            </li>
            <li className="pt-4">
              <span class="font-semibold">Smart Devices:</span>The proliferation
              of smart devices, such as smartphones, tablets, and wearable
              gadgets, further accelerated the development of IoT. These devices
              are equipped with sensors, actuators, and connectivity features,
              making them capable of interacting with the physical world and
              exchanging data over the internet.
            </li>
            <li className="pt-4">
              <span class="font-semibold">Cloud Computing:</span>The rise of
              cloud computing, which refers to the storage and processing of
              data on remote servers accessed via the internet, has been crucial
              for IoT. Cloud platforms provide scalable and reliable storage for
              the massive amounts of data generated by IoT devices. They also
              enable advanced data analysis and machine learning algorithms to
              extract valuable insights from the data.
            </li>
            <li className="pt-4">
              <span class="font-semibold">
                Interconnectivity and Standards:{" "}
              </span>
              To enable seamless communication and interoperability between
              different IoT devices and platforms, various standards and
              protocols have been developed. These standards ensure that devices
              from different manufacturers can work together. Examples include
              Wi-Fi, Bluetooth, Zigbee, and MQTT (Message Queuing Telemetry
              Transport).
            </li>
            <li className="pt-4">
              <span class="font-semibold">Applications:</span>IoT has found
              applications in various fields, including smart homes,
              agriculture, healthcare, transportation, and more. For example, in
              a smart home, IoT devices can be used to control lights,
              thermostats, security systems, and even kitchen appliances.
            </li>
          </ul>

          <p className="text-justify p-2 pt-4">
            Please note that explaining the code for the entire evolution of IoT
            would be impractical as it involves a vast and complex body of work.
            However, I can provide you with a simple example of an IoT project
            using Arduino, which will help you understand how devices can be
            connected and controlled. Let's continue with that:
          </p>
          <h4 className="p-2 m-2 text-lg font-bold">
            Imagine you have a smart light bulb that can be controlled using a
            smartphone app. You can turn it on and off, adjust the brightness,
            and change the color. Here's a simplified example of the code using
            Arduino:
          </h4>

          <CodeHighlighter>{codeString}</CodeHighlighter>

          <p className="text-justify p-2 pt-4">
            In this code, we include the necessary libraries for Wi-Fi and
            controlling NeoPixel LEDs. We define the Wi-Fi credentials to
            connect to your network. We create an instance of the NeoPixel
            library, specifying the number of LEDs and the pin to which they are
            connected. In the setup() function, we connect to Wi-Fi and
            initialize the NeoPixel strip. The loop() function is where you
            would write the code for controlling the light bulb, such as turning
            it on and off or changing its color.
          </p>
          <p className="text-justify p-2 pt-4">
            Remember that this is a simplified example, and an actual IoT
            project would involve more complex code, hardware, and integration
            with cloud services.
          </p>
        </article>
      </section>
    </div>
  );
};

export default IoTIntroHistorical;
